=== BloodsFa1zer/blank-project/src/main/resources/xsd/gems.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           targetNamespace="http://www.diamondfund.ua/gems"
           xmlns:gems="http://www.diamondfund.ua/gems">

    <!-- Simple Types -->
    <xs:simpleType name="preciousnessType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="precious"/>
            <xs:enumeration value="semi-precious"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="colorType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="green"/>
            <xs:enumeration value="red"/>
            <xs:enumeration value="yellow"/>
            <xs:enumeration value="blue"/>
            <xs:enumeration value="white"/>
            <xs:enumeration value="pink"/>
            <xs:enumeration value="purple"/>
            <xs:enumeration value="orange"/>
            <xs:enumeration value="black"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="transparencyType">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="100"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="facetsType">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="4"/>
            <xs:maxInclusive value="15"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="valueType">
        <xs:restriction base="xs:decimal">
            <xs:minExclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Complex Type: Visual Parameters -->
    <xs:complexType name="visualParametersType">
        <xs:sequence>
            <xs:element name="color" type="gems:colorType" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="transparency" type="gems:transparencyType"/>
            <xs:element name="facets" type="gems:facetsType"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Complex Type: Gem -->
    <xs:complexType name="gemType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="preciousness" type="gems:preciousnessType"/>
            <xs:element name="origin" type="xs:string"/>
            <xs:element name="visualParameters" type="gems:visualParametersType" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="value" type="gems:valueType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>

    <!-- Root Element -->
    <xs:element name="Gem">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="gem" type="gems:gemType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== BloodsFa1zer/blank-project/src/main/resources/xml/gems.xml
<?xml version="1.0" encoding="UTF-8"?>
<Gem xmlns="http://www.diamondfund.ua/gems"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://www.diamondfund.ua/gems ../xsd/gems.xsd">
    <gem id="gem001">
        <name>Diamond</name>
        <preciousness>precious</preciousness>
        <origin>South Africa</origin>
        <visualParameters>
            <color>white</color>
            <transparency>95</transparency>
            <facets>12</facets>
        </visualParameters>
        <value>2.5</value>
    </gem>
    <gem id="gem002">
        <name>Ruby</name>
        <preciousness>precious</preciousness>
        <origin>Myanmar</origin>
        <visualParameters>
            <color>red</color>
            <transparency>85</transparency>
            <facets>8</facets>
        </visualParameters>
        <value>1.8</value>
    </gem>
    <gem id="gem003">
        <name>Emerald</name>
        <preciousness>precious</preciousness>
        <origin>Colombia</origin>
        <visualParameters>
            <color>green</color>
            <transparency>75</transparency>
            <facets>10</facets>
        </visualParameters>
        <value>3.2</value>
    </gem>
    <gem id="gem004">
        <name>Amethyst</name>
        <preciousness>semi-precious</preciousness>
        <origin>Brazil</origin>
        <visualParameters>
            <color>purple</color>
            <transparency>80</transparency>
            <facets>6</facets>
        </visualParameters>
        <value>5.0</value>
    </gem>
    <gem id="gem005">
        <name>Topaz</name>
        <preciousness>semi-precious</preciousness>
        <origin>Russia</origin>
        <visualParameters>
            <color>yellow</color>
            <color>blue</color>
            <transparency>88</transparency>
            <facets>9</facets>
        </visualParameters>
        <value>4.5</value>
    </gem>
    <gem id="gem006">
        <name>Sapphire</name>
        <preciousness>precious</preciousness>
        <origin>Sri Lanka</origin>
        <visualParameters>
            <color>blue</color>
            <transparency>90</transparency>
            <facets>14</facets>
        </visualParameters>
        <value>2.1</value>
    </gem>
    <gem id="gem007">
        <name>Garnet</name>
        <preciousness>semi-precious</preciousness>
        <origin>India</origin>
        <visualParameters>
            <color>red</color>
            <transparency>70</transparency>
            <facets>5</facets>
        </visualParameters>
        <value>3.8</value>
    </gem>
</Gem>
